name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: maximgorbatyuk/hugo-blog@main
        env:
          HUGO_VERSION: 0.80.0
          TARGET_REPO: maximgorbatyuk/maximgorbatyuk.github.io
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: '-t academic'
          CNAME: maximgorbatyuk.github.io